(() => {
 'use strict';
 const $=id=>document.getElementById(id),api=window.detectorData;let facilityId='',facilities=[],orders=[],register={devices:[],events:[]},parsed=null,importPlan=null,selected=null;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const btn=(text,fn)=>{const b=el('button',text);b.type='button';b.className='secondary';b.onclick=fn;return b;};
 const msg=text=>$('det-message').textContent=text;
 const model=()=>facilities.find(f=>f.id===facilityId)?.central||'';let queue=[],running=false;
 const inScope=d=>(!$('det-loop').value||Number(d.slinga)===Number($('det-loop').value))&&(!$('det-section').value||Number(d.sektion)===Number($('det-section').value));
 const key=()=>`detectors:${facilityId}`;
 async function refresh(){facilities=await window.localData.read('facilities',[]);orders=await window.localData.read('workorders',[]);const select=$('det-facility');select.replaceChildren(el('option','Välj objekt'));select.firstChild.value='';for(const f of facilities){const o=el('option',`${f.anlNr||''} · ${f.namn}`);o.value=f.id;select.append(o);}select.value=facilityId;register=facilityId?await window.localData.read(key(),{devices:[],events:[]}):{devices:[],events:[]};render();}
 async function mutate(fn){if(!facilityId)throw Error('Välj objekt först.');await window.localData.updateRecord(key(),{devices:[],events:[]},fn);register=await window.localData.read(key());render();}
 function download(name,body){const url=URL.createObjectURL(new Blob([body],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function render(){const from=$('det-from').value||'0000-01-01',to=$('det-to').value||'9999-12-31',q=$('det-search').value.toLocaleLowerCase('sv'),mode=$('det-filter').value;const done=register.devices.filter(d=>api.tested(d,register.events,from,to)).length;$('det-count').textContent=`${register.devices.length} registrerade · ${done} provade · ${register.devices.length-done} återstår under perioden`;
  const rows=register.devices.filter(inScope).filter(d=>[api.label(d,model()),...api.fields.map(([k])=>d[k])].join(' ').toLocaleLowerCase('sv').includes(q)).filter(d=>mode!=='remaining'||!api.tested(d,register.events,from,to)).sort((a,b)=>(api.latest(a,register.events)?.date||'').localeCompare(api.latest(b,register.events)?.date||'')||a.adress.localeCompare(b.adress,'sv',{numeric:true}));$('det-list').replaceChildren();if(!rows.length)$('det-list').append(el('p','Inga detektorer i detta urval. Importera eller lägg till manuellt.'));
  for(const d of rows){const card=el('article');card.className='job-card';const last=api.latest(d,register.events);card.append(el('strong',`${api.label(d,model())} · ${d.typ||'Typ saknas'}`),el('p',[d.central,d.slinga,d.placering].filter(Boolean).join(' · ')),el('p',last?`Senaste registrering: ${last.date} · ${last.status}`:'Ingen provning registrerad för denna detektor'));const actions=el('div');actions.className='button-row';actions.append(btn('Registrera provning',()=>{running=false;queue=[];openTest(d);}),btn('Historik',()=>history(d)),btn('Redigera',()=>edit(d)),btn('Registrera byte',async()=>{const note=prompt('Beskriv detektorbytet. Historiken behålls; den nya detektorn räknas som oprövad.');if(!note?.trim())return;try{await mutate(r=>{const current=r.devices.find(x=>x.id===d.id);if(!current)throw Error('Detektorn saknas.');r.events.push({id:crypto.randomUUID(),kind:'replacement',deviceId:d.id,generation:current.generation,date:window.orderData.today(),recordedAt:new Date().toISOString(),note:note.trim(),device:{...current}});current.generation++;return r;});msg('Byte registrerat. Redigera typ och placering vid behov.');}catch(e){msg(e.message);}}));card.append(actions);$('det-list').append(card);}
 }
 function edit(device){if(!facilityId){msg('Välj objekt först.');return;}selected=device||null;const form=$('det-edit');form.replaceChildren(el('h3',device?'Redigera detektor':'Ny detektor'));for(const [key,label]of api.fields){const l=el('label',label),input=el('input');input.name=key;input.value=device?.[key]||'';input.required=key==='adress';l.append(input);form.append(l);}const save=el('button','Spara detektor');save.className='primary';save.type='submit';form.append(save,btn('Avbryt',()=>form.hidden=true));form.hidden=false;form.scrollIntoView({block:'center'});}
 $('det-edit').onsubmit=async e=>{e.preventDefault();let values=Object.fromEntries(new FormData(e.target));try{values=api.splitAddress(values,model());await mutate(r=>{if(r.devices.some(d=>d.id!==selected?.id&&api.identity(d)===api.identity(values)))throw Error('Central, slinga och adress finns redan.');if(selected){const d=r.devices.find(d=>d.id===selected.id);if(!d)throw Error('Detektorn saknas.');Object.assign(d,values);}else r.devices.push({...values,id:crypto.randomUUID(),generation:1});return r;});e.target.hidden=true;msg('Detektorn sparades.');}catch(error){msg(error.message);}};
 async function openTest(d){orders=await window.localData.read('workorders',[]);selected=d;$('det-test-title').textContent=`Provning: ${api.label(d,model())} · ${d.placering}`;if(!running||!$('det-test-date').value)$('det-test-date').value=window.orderData.today();$('det-test-status').value='';for(const b of $('det-result-buttons').children)b.setAttribute('aria-pressed','false');$('det-test-note').value='';$('det-test-photo').value='';const select=$('det-test-order');const previous=select.value;select.replaceChildren();for(const o of orders.filter(o=>o.facilityId===facilityId&&o.status!=='Klart')){const option=el('option',`${o.ordernummer} · ${o.uppdragstyp}`);option.value=o.id;select.append(option);}if([...select.options].some(o=>o.value===previous))select.value=previous;$('det-test').hidden=false;$('det-test').scrollIntoView({block:'center'});}
 $('det-test').onsubmit=async e=>{e.preventDefault();const button=$('det-test-save'),targetFacility=facilityId,targetDevice=selected;button.disabled=true;try{const order=orders.find(o=>o.id===$('det-test-order').value);if(!order||order.facilityId!==facilityId)throw Error('Skapa en öppen arbetsorder på objektet först.');let photo='';const file=$('det-test-photo').files[0];if(file){if(file.size>2*1024*1024)throw Error('Fotot får vara högst 2 MB. Välj en mindre bild.');if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error('Välj ett JPEG-, PNG- eller WebP-foto.');photo=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});}const input={label:api.label(targetDevice,model()),date:$('det-test-date').value,technician:$('det-technician').value.trim(),orderId:order.id,orderNumber:order.ordernummer,status:$('det-test-status').value,note:$('det-test-note').value.trim(),photo};if(facilityId!==targetFacility||selected!==targetDevice)throw Error('Objektet ändrades. Öppna provningen igen.');await mutate(r=>{const d=r.devices.find(d=>d.id===targetDevice.id);if(!d||d.generation!==targetDevice.generation)throw Error('Detektorn har ändrats. Öppna provningen igen.');r.events.push(api.event(d,input));return r;});e.target.hidden=true;msg('Provningen sparades som en ny historikhändelse.');if(running){queue.shift();if(queue.length){await openTest(register.devices.find(d=>d.id===queue[0]));}else{running=false;msg('Urvalet är klart. Resultaten följer med till BL401 för samma datum och arbetsorder.');}}}catch(error){msg(error.message);}finally{button.disabled=false;}};
 function history(d){const panel=$('det-history');panel.replaceChildren(el('h3',`Historik: ${api.label(d,model())} · ${d.placering}`),btn('Stäng',()=>panel.hidden=true));const events=register.events.filter(e=>e.deviceId===d.id).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt));for(const e of events){const item=el('article');item.className='job-card';item.append(el('strong',`${e.label||api.label(e.device||d,model())} · ${e.date} · ${e.kind==='replacement'?'Detektorbyte':e.status} · generation ${e.generation}`),el('p',[e.technician,e.orderNumber,e.note].filter(Boolean).join(' · ')));if(e.photo&&/^data:image\/(jpeg|png|webp);base64,/.test(e.photo)){const img=el('img');img.src=e.photo;img.alt='Foto från provningen';img.style.maxWidth='100%';item.append(img);}panel.append(item);}if(!events.length)panel.append(el('p','Ingen historik ännu.'));panel.hidden=false;panel.scrollIntoView({block:'center'});}
 function normalizedRows(rows,mapping){return rows.map(row=>{const value=Object.fromEntries(mapping.map((k,i)=>[k,row[i]]));const d=api.splitAddress(value,model());return mapping.map((k,i)=>d[k]??row[i]);});}
 function resetImport(){parsed=null;importPlan=null;$('det-map').replaceChildren();$('det-preview').replaceChildren();$('det-import-save').disabled=true;}
 async function preview(){try{if(!facilityId)throw Error('Välj objekt först.');register=await window.localData.read(key(),{devices:[],events:[]});const mapping=[...$('det-map').querySelectorAll('select')].map(s=>s.value);importPlan=api.plan(normalizedRows(parsed.rows,mapping),mapping,register.devices);$('det-preview').replaceChildren();for(const entry of importPlan){$('det-preview').append(el('p',`${entry.action}: ${api.fields.map(([k])=>entry.device[k]).filter(Boolean).join(' · ')}`));}$('det-import-save').disabled=false;msg(`${importPlan.length} detektorer granskade. Samma central, slinga och adress uppdaterar uppgifter; historiken bevaras.`);}catch(e){importPlan=null;$('det-import-save').disabled=true;msg(e.message);}}
 $('det-review').onclick=()=>{try{parsed=window.objectLists.parse($('det-text').value);if(!parsed.headers.some(h=>h.trim().toLowerCase()==='slinga')){parsed.headers.push('Slinga');parsed.rows.forEach(row=>row.push(''));}$('det-map').replaceChildren();parsed.headers.forEach(header=>{const label=el('label',header),select=el('select');for(const [key,text]of [['','Hoppa över'],...api.fields]){const option=el('option',text);option.value=key;select.append(option);}const h=header.toLocaleLowerCase('sv').trim();select.value=api.fields.find(([key,text])=>key===h||text.toLocaleLowerCase('sv')===h)?.[0]||'';select.onchange=preview;label.append(select);$('det-map').append(label);});preview();}catch(e){msg(e.message);}};
 $('det-import-save').onclick=async()=>{if(!importPlan)return;try{if(!confirm('Importera detektorerna? Befintlig historik behålls. Tomma fält raderar inte uppgifter.'))return;const mapping=[...$('det-map').querySelectorAll('select')].map(s=>s.value);await mutate(r=>{const plan=api.plan(normalizedRows(parsed.rows,mapping),mapping,r.devices);for(const {device}of plan){const i=r.devices.findIndex(d=>d.id===device.id);if(i>=0)r.devices[i]=device;else r.devices.push(device);}return r;});resetImport();$('det-text').value='';msg('Detektorlistan är importerad.');}catch(e){msg(e.message);}};
 $('det-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw Error('Filen får vara högst 5 MB.');$('det-text').value=await file.text();resetImport();}catch(error){msg(error.message);}finally{e.target.value='';}};$('det-text').oninput=resetImport;
 $('det-facility').onchange=async e=>{facilityId=e.target.value;selected=null;running=false;queue=[];for(const id of ['det-edit','det-test','det-history'])$(id).hidden=true;resetImport();await refresh();};
 $('det-new').onclick=()=>edit(null);$('det-test-cancel').onclick=()=>{running=false;queue=[];$('det-test').hidden=true;};
 $('det-start').onclick=async()=>{if(!facilityId){msg('Välj objekt först.');return;}const from=$('det-from').value||'0000-01-01',to=$('det-to').value||'9999-12-31';const q=$('det-search').value.toLocaleLowerCase('sv');queue=register.devices.filter(inScope).filter(d=>[api.label(d,model()),...api.fields.map(([k])=>d[k])].join(' ').toLocaleLowerCase('sv').includes(q)).filter(d=>!api.tested(d,register.events,from,to)).sort((a,b)=>(api.latest(a,register.events)?.date||'').localeCompare(api.latest(b,register.events)?.date||'')||api.label(a,model()).localeCompare(api.label(b,model()),'sv',{numeric:true})).map(d=>d.id);if(!queue.length){msg('Inga återstående detektorer i urvalet.');return;}running=true;await openTest(register.devices.find(d=>d.id===queue[0]));};
 for(const status of api.statuses){const b=btn(status,()=>{$('det-test-status').value=status;for(const button of $('det-result-buttons').children)button.setAttribute('aria-pressed',String(button===b));});$('det-result-buttons').append(b);}
 $('det-template').onclick=()=>download('detektormall.csv',api.csv([api.fields.map(f=>f[1])]));
 $('det-export').onclick=()=>{const from=$('det-from').value||'0000-01-01',to=$('det-to').value||'9999-12-31';const rows=[['Beteckning','Central','Slinga','Sektion','Adress','Typ','Placering','Generation','Provad i perioden','Senaste datum','Senaste resultat']];for(const d of register.devices){const last=api.latest(d,register.events);rows.push([api.label(d,model()),...api.fields.map(([k])=>d[k]),d.generation,api.tested(d,register.events,from,to)?'Ja':'Nej',last?.date||'',last?.status||'']);}download('provningslista.csv',api.csv(rows));};
 $('det-export-history').onclick=()=>{const rows=[['Beteckning','Datum','Central','Slinga','Sektion','Adress','Typ','Placering','Generation','Resultat','Tekniker','Ordernummer','Kommentar','Registrerad']];for(const e of register.events)rows.push([e.label||api.label(e.device||{},model()),e.date,...api.fields.map(([k])=>e.device?.[k]||''),e.generation,e.kind==='replacement'?'Detektorbyte':e.status,e.technician||'',e.orderNumber||'',e.note||'',e.recordedAt]);download('provningshistorik.csv',api.csv(rows));};
 for(const id of ['det-from','det-to','det-filter','det-search','det-loop','det-section'])$(id).oninput=render;
 $('det-from').value=new Date().getFullYear()+'-01-01';$('det-to').value=window.orderData.today();
 window.addEventListener('field-test',async e=>{try{facilityId=e.detail.id;await refresh();queue=(e.detail.deviceIds||[e.detail.deviceId]).filter(id=>register.devices.some(d=>d.id===id));if(!queue.length){msg('Inga återstående detektorer i arbetslistan.');return;}running=queue.length>1;$('detectors-panel').open=true;await openTest(register.devices.find(d=>d.id===queue[0]));}catch(e){msg(e.message);}});window.addEventListener('open-detectors',async e=>{running=false;queue=[];selected=null;$('det-test').hidden=true;facilityId=e.detail.id;$('detectors-panel').open=true;await refresh();$('detectors-panel').scrollIntoView({block:'start'});});window.addEventListener('objects-imported',refresh);window.localReady.then(refresh).catch(e=>msg(e.message));
})();
