/* Field tools: pure planning, validation and object-package helpers. */
(() => {
 'use strict';
 const phases=['Förberedelser','Provning','Återställning','Dokumentation'];
 const templates=Object.fromEntries(['SK','KV','SB'].map(kind=>[kind,phases.map((phase,i)=>({phase,text:[`Bekräfta uppdragets omfattning (${kind}) och kontaktperson.`,`Genomför och dokumentera överenskomna provningar.`,`Kontrollera och dokumentera återställning av berörda funktioner.`,`Gå igenom kvarstående fel, nästa åtgärd och rapport.`][i]}))]));
 const phrases=['Detektor ej åtkomlig.','Märkning saknas.','Ritning behöver uppdateras.','Åtgärd behöver bokas med kontaktperson.'];
 const empty=()=>({visits:[],materials:[],plans:[],pins:[],prep:''});
 const read=(data,key,fallback)=>JSON.parse(data[key]??JSON.stringify(fallback));
 function date(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(+new Date(value))||new Date(value).toISOString().slice(0,10)!==value)throw Error('Ange ett giltigt datum.');return value;}
 function candidates(register,from,to,model){date(from);date(to);if(from>to)throw Error('Från datum måste vara före till datum.');return register.devices.filter(d=>!window.detectorData.tested(d,register.events,from,to)).sort((a,b)=>(window.detectorData.latest(a,register.events)?.date||'').localeCompare(window.detectorData.latest(b,register.events)?.date||'')||window.detectorData.label(a,model).localeCompare(window.detectorData.label(b,model),'sv',{numeric:true}));}
 function material(v){const quantity=Number(v.quantity);if(!v.name?.trim()||!Number.isInteger(quantity)||quantity<1||quantity>100000)throw Error('Ange artikel och ett helt antal större än noll.');if(v.installed)date(v.installed);if(v.state&&!['Installerat','Behöver beställas','Beställt','Att ta med','Förbrukat'].includes(v.state))throw Error('Ogiltig materialstatus.');return {id:v.id||crypto.randomUUID(),name:v.name.trim(),model:String(v.model||'').trim(),quantity,installed:v.installed||'',state:v.state||'Installerat',note:String(v.note||'').trim()};}
 function validateField(v){if(!v||!['visits','materials','plans','pins'].every(k=>Array.isArray(v[k])))throw Error('Fältverktygens data har fel format.');for(const key of ['visits','materials','plans','pins'])if(v[key].some(x=>!x||typeof x.id!=='string'))throw Error('En fältpost saknar ID.');for(const p of v.pins)if(typeof p.docId!=='string'||typeof p.deviceId!=='string'||!Number.isInteger(p.page)||p.page<1||!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>1||p.y<0||p.y>1)throw Error('En ritningsmarkering är ogiltig.');for(const v0 of v.visits)if(!Array.isArray(v0.items)||v0.items.some(i=>typeof i?.id!=='string'||typeof i.text!=='string'||!phases.includes(i.phase)||!['Återstår','Klart','Ej aktuellt'].includes(i.status)))throw Error('En besökschecklista är ogiltig.');for(const m of v.materials)material(m);for(const p of v.plans){date(p.from);date(p.to);if(p.from>p.to||!Array.isArray(p.devices)||p.devices.some(d=>typeof d?.id!=='string'))throw Error('En provningsplan är ogiltig.');}return v;}
 function packageObject(data,id){const f=read(data,'facilities',[]).find(f=>f.id===id);if(!f)throw Error('Objektet saknas.');const orders=read(data,'workorders',[]).filter(o=>o.facilityId===id),history=read(data,'history-index',[]).filter(r=>r.facilityId===id),docs=read(data,'docs:'+id,[]),out={facilities:JSON.stringify([f]),workorders:JSON.stringify(orders),'history-index':JSON.stringify(history)};
  const keys=[...['docs','materiel','detectors','issues','service-reports','fieldwork'].map(k=>k+':'+id),...docs.map(d=>'docfile:'+d.id),...history.map(r=>'report:'+r.id)];
  for(const key of Object.keys(data))if(key.startsWith('draft:')&&[id,...orders.map(o=>o.id)].some(owner=>key.startsWith('draft:'+owner+':')))keys.push(key);
  for(const key of keys)if(data[key]!==undefined)out[key]=data[key];
  return {app:'SäkerhetSnabben objektpaket',version:1,exportedAt:new Date().toISOString(),facilityId:id,data:out};
 }
 function validatePackage(pkg){if(!pkg||pkg.app!=='SäkerhetSnabben objektpaket'||pkg.version!==1||typeof pkg.facilityId!=='string'||!pkg.data||Array.isArray(pkg.data))throw Error('Välj ett objektpaket från SäkerhetSnabben.');const data=pkg.data;for(const v of Object.values(data))if(typeof v!=='string')throw Error('Ogiltigt objektpaket.');
  const fs=read(data,'facilities',[]),orders=read(data,'workorders',[]),history=read(data,'history-index',[]);if(!Array.isArray(fs)||fs.length!==1||fs[0].id!==pkg.facilityId||typeof fs[0].namn!=='string'||!Array.isArray(orders)||!Array.isArray(history))throw Error('Paketet ska innehålla exakt ett kundobjekt.');if(orders.some(o=>!o||typeof o.id!=='string'||o.facilityId!==pkg.facilityId)||history.some(r=>!r||typeof r.id!=='string'||r.facilityId!==pkg.facilityId))throw Error('Paketet innehåller poster för ett annat objekt.');
  const canonical=packageObject(data,pkg.facilityId).data;if(Object.keys(data).some(k=>!Object.hasOwn(canonical,k)))throw Error('Paketet innehåller orelaterade poster.');
  for(const prefix of ['docs','materiel','issues','service-reports']){const a=read(data,prefix+':'+pkg.facilityId,[]);if(!Array.isArray(a)||a.some(x=>!x||typeof x.id!=='string'))throw Error('Ett register är ogiltigt.');}
  if(data['fieldwork:'+pkg.facilityId])validateField(read(data,'fieldwork:'+pkg.facilityId));
  const reg=read(data,'detectors:'+pkg.facilityId,{devices:[],events:[]});if(!Array.isArray(reg.devices)||!Array.isArray(reg.events)||reg.devices.some(d=>typeof d.id!=='string'||typeof d.adress!=='string'||!Number.isInteger(d.generation)||d.generation<1)||reg.events.some(e=>typeof e.id!=='string'||typeof e.deviceId!=='string'||!['test','replacement'].includes(e.kind)))throw Error('Detektorregistret är ogiltigt.');
  for(const d of read(data,'docs:'+pkg.facilityId,[])){const content=read(data,'docfile:'+d.id,'');if(typeof content!=='string'||!/^data:(?:image\/(?:jpeg|png|webp)|application\/pdf);base64,[A-Za-z0-9+/=\r\n]+$/.test(content))throw Error('En dokumentfil saknas eller har ett format som inte stöds.');}
  for(const [k,v]of Object.entries(data))if(k.startsWith('draft:')&&JSON.parse(v)?.facility?.id!==pkg.facilityId)throw Error('Ett utkast tillhör ett annat objekt.');for(const r of history){const report=read(data,'report:'+r.id,null);if(!report||report.facility?.id!==pkg.facilityId)throw Error('Ett protokoll saknas eller tillhör ett annat objekt.');}return pkg;
 }
 function previewPackage(pkg,current){validatePackage(pkg);const f=read(pkg.data,'facilities')[0],facilities=read(current,'facilities',[]);if(facilities.some(x=>x.id!==f.id&&f.anlNr&&String(x.anlNr).trim().toLowerCase()===String(f.anlNr).trim().toLowerCase()))throw Error('Objektnumret finns med ett annat internt ID. Importen stoppades för att undvika dubbla objekt.');
  const rows=[];for(const [key,value]of Object.entries(pkg.data)){
   if(['facilities','workorders','history-index'].includes(key)){const local=read(current,key,[]);for(const item of JSON.parse(value)){const old=local.find(x=>x.id===item.id);if(old&&key!=='facilities'&&old.facilityId!==f.id)throw Error('En post kolliderar med ett annat objekt.');rows.push({key,id:item.id,label:(key==='facilities'?'Objektuppgifter':key==='workorders'?'Arbetsorder':'Protokoll')+' · '+(item.ordernummer||item.proto||f.namn),before:old===undefined?undefined:JSON.stringify(old),after:JSON.stringify(item)});}}
   else{if(key.startsWith('docfile:')){const docId=key.slice(8);if(Object.entries(current).some(([k,v])=>k.startsWith('docs:')&&k!=='docs:'+f.id&&JSON.parse(v).some(d=>d.id===docId)))throw Error('En dokumentfil används av ett annat objekt.');}rows.push({key,label:key.split(':')[0],before:current[key],after:value});}
  }return rows.map(r=>({...r,kind:r.before===undefined?'Ny':r.before===r.after?'Oförändrad':'Skillnad',use:r.before===undefined}));
 }
 function packageWrites(rows,current){const writes={};for(const row of rows.filter(r=>r.use&&r.kind!=='Oförändrad')){if(row.id){const list=JSON.parse(writes[row.key]??current[row.key]??'[]'),i=list.findIndex(x=>x.id===row.id);if(i<0)list.push(JSON.parse(row.after));else list[i]=JSON.parse(row.after);writes[row.key]=JSON.stringify(list);}else writes[row.key]=row.after;}return writes;}
 window.fieldData={phases,templates,phrases,empty,read,date,candidates,material,validateField,packageObject,validatePackage,previewPackage,packageWrites};
})();
