(() => {
 'use strict';
 const api=window.fieldData,db=window.localData;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const btn=(text,fn)=>{const b=el('button',text,'secondary');b.type='button';b.onclick=fn;return b;};
 function input(parent,title,name,value='',type='text'){const label=el('label',title),n=el(type==='textarea'?'textarea':'input');if(type!=='textarea')n.type=type;else n.rows=3;n.name=name;n.value=value;label.append(n);parent.append(label);return n;}
 function select(parent,title,values,value){const label=el('label',title),n=el('select');for(const [v,t]of values){const o=el('option',t);o.value=v;n.append(o);}if(value!==undefined)n.value=value;label.append(n);parent.append(label);return n;}
 function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 const root=el('div',undefined,'service-hub field-hub');let signature='',active='',prefs={templates:api.templates,phrases:api.phrases};
 const refresh=()=>window.dispatchEvent(new Event('service-changed'));
 async function quick(inputNode){if(inputNode.dataset.quick)return;inputNode.dataset.quick='yes';const p=await db.read('field-preferences',{templates:api.templates,phrases:api.phrases}),box=el('div',undefined,'quick-texts');const s=select(box,'Infoga snabbtext',[['','Välj snabbtext'],...(p.phrases||api.phrases).map(t=>[t,t])]);s.onchange=()=>{if(s.value){inputNode.value+=(inputNode.value?'\n':'')+s.value;inputNode.dispatchEvent(new Event('input',{bubbles:true}));s.value='';inputNode.focus();}};inputNode.parentElement.after(box);}
 function mount(container,f,data){container.append(root);const next=JSON.stringify([f,...['fieldwork:'+f.id,'docs:'+f.id,'detectors:'+f.id,'issues:'+f.id,'service-reports:'+f.id,'materiel:'+f.id,'history-index','workorders','field-preferences'].map(k=>data[k])]);if(active===f.id&&signature===next)return;
  const drawingState=active===f.id?{doc:root.querySelector('[data-drawing=doc]')?.value,page:root.querySelector('[data-drawing=page]')?.value,zoom:root.querySelector('[data-drawing=zoom]')?.value,from:root.querySelector('[data-drawing=from]')?.value,to:root.querySelector('[data-drawing=to]')?.value}:{};root.cleanup?.();const opens=new Set([...root.querySelectorAll('details[data-panel][open]')].map(n=>n.dataset.panel));if(active!==f.id)opens.clear();active=f.id;signature=next;root.replaceChildren();prefs=api.read(data,'field-preferences',{templates:api.templates,phrases:api.phrases});
  const state=api.read(data,'fieldwork:'+f.id,api.empty()),register=api.read(data,'detectors:'+f.id,{devices:[],events:[]}),docs=api.read(data,'docs:'+f.id,[]),orders=api.read(data,'workorders',[]).filter(o=>o.facilityId===f.id),message=el('p');message.setAttribute('role','status');root.append(el('h3','Verktyg inför och under besöket'),message);
  const error=e=>message.textContent=e.message||String(e);
  async function save(fn){await db.updateRecord('fieldwork:'+f.id,api.empty(),s=>{fn(s);return api.validateField(s);});refresh();}
  function panel(key,title){const p=el('details',undefined,'settings-card');p.dataset.panel=key;p.open=opens.has(key);p.append(el('summary',title));root.append(p);return p;}
  const checklist=panel('checklist','1 · Besökschecklistor');checklist.append(el('p','Egna arbetssteg för SK, KV och SB. Påbörjade listor sparas på objektet. Anpassa mallen efter uppdraget.'));
  const start=el('form',undefined,'import-grid'),kind=select(start,'Typ',[['SK','SK'],['KV','KV'],['SB','SB']]),visitDate=input(start,'Besöksdatum','date',window.orderData.today(),'date'),order=select(start,'Koppla till order',[['','Utan order'],...orders.map(o=>[o.id,o.ordernummer+' · '+o.uppdragstyp])]),create=el('button','Starta besökschecklista','primary');create.type='submit';start.append(create);checklist.append(start);
  start.onsubmit=async e=>{e.preventDefault();create.disabled=true;try{api.date(visitDate.value);const t=prefs.templates?.[kind.value]||api.templates[kind.value];if(!t.length)throw Error('Lägg till minst ett steg i mallen.');await save(s=>s.visits.unshift({id:crypto.randomUUID(),kind:kind.value,date:visitDate.value,orderId:order.value,items:t.map(i=>({...i,id:crypto.randomUUID(),status:'Återstår',note:'',at:''})),closedAt:''}));}catch(e){error(e);create.disabled=false;}};
  const template=el('details');template.append(el('summary','Redigera egna mallar (på denna enhet)'));const tf=el('form'),areas={};for(const k of ['SK','KV','SB'])areas[k]=input(tf,k+' – en rad per steg, fas | beskrivning',k,(prefs.templates?.[k]||api.templates[k]).map(i=>i.phase+' | '+i.text).join('\n'),'textarea');tf.append(el('p','Faser: '+api.phases.join(', ')));const ts=el('button','Spara mallar','primary');tf.append(ts);tf.onsubmit=async e=>{e.preventDefault();try{const t={};for(const k of ['SK','KV','SB']){t[k]=areas[k].value.split('\n').filter(x=>x.trim()).map(line=>{const at=line.indexOf('|'),phase=line.slice(0,at).trim(),text=line.slice(at+1).trim();if(at<0||!api.phases.includes(phase)||!text)throw Error('Skriv fas | beskrivning på varje rad.');return {phase,text};});if(!t[k].length)throw Error('Varje mall behöver minst ett steg.');}await db.updateRecord('field-preferences',{templates:api.templates,phrases:api.phrases},p=>({...p,templates:t}));refresh();}catch(e){error(e);}};template.append(tf);checklist.append(template);
  for(const visit of state.visits){const card=el('details',undefined,'job-card');card.open=!visit.closedAt;card.append(el('summary',visit.date+' · '+visit.kind+' · '+(visit.closedAt?'Avslutad':visit.items.filter(i=>i.status!=='Återstår').length+'/'+visit.items.length+' dokumenterade steg')));if(visit.orderId)card.append(el('p','Order: '+(orders.find(o=>o.id===visit.orderId)?.ordernummer||'Saknas')));
   for(const phase of api.phases){const items=visit.items.filter(i=>i.phase===phase);if(!items.length)continue;card.append(el('h4',phase));for(const item of items){const row=el('form',undefined,'job-card');row.append(el('strong',item.text));const status=select(row,'Stegstatus',[['Återstår','Återstår'],['Klart','Klart'],['Ej aktuellt','Ej aktuellt']],item.status),note=input(row,'Anteckning / skäl vid Ej aktuellt','note',item.note,'textarea');status.disabled=!!visit.closedAt;note.disabled=!!visit.closedAt;if(!visit.closedAt){const b=el('button','Spara steg','primary');row.append(b);row.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{if(status.value==='Ej aktuellt'&&!note.value.trim())throw Error('Ange varför steget inte är aktuellt.');await save(s=>{const v=s.visits.find(v=>v.id===visit.id);if(!v||v.closedAt)throw Error('Besöket har ändrats.');const it=v.items.find(i=>i.id===item.id);if(!it)throw Error('Steget saknas.');Object.assign(it,{status:status.value,note:note.value.trim(),at:new Date().toISOString()});});}catch(e){error(e);b.disabled=false;}};}card.append(row);}}
   card.append(btn(visit.closedAt?'Återöppna checklista':'Avsluta checklista',async()=>{try{await save(s=>{const v=s.visits.find(v=>v.id===visit.id);if(!v)throw Error('Besöket saknas.');if(!v.closedAt&&v.items.some(i=>i.status==='Återstår'))throw Error('Dokumentera återstående steg innan checklistan avslutas.');v.closedAt=v.closedAt?'':new Date().toISOString();});}catch(e){error(e);}}));checklist.append(card);
  }
  const drawings=panel('drawings','2 · Detektorer på ritningen');drawings.append(el('p','Välj en sparad bild eller PDF. Välj detektor och aktivera placering, tryck sedan på ritningen. Markeringarnas färg gäller vald period.'));
  const ds=select(drawings,'Ritning',[['','Välj dokument'],...docs.filter(d=>/pdf|image\//.test(d.mime)).map(d=>[d.id,d.description||d.namn])]),controls=el('div',undefined,'import-grid'),page=input(controls,'PDF-sida','page','1','number'),from=input(controls,'Provning från','from',new Date().getFullYear()+'-01-01','date'),to=input(controls,'Provning till','to',window.orderData.today(),'date');page.min='1';const device=select(controls,'Detektor att placera',[['','Välj detektor'],...register.devices.map(d=>[d.id,window.detectorData.label(d,f.central)+' · '+d.placering])]);drawings.append(controls);let placing=false,docHandle=null,renderTask=null,renderVersion=0;
  const place=btn('Aktivera placering',()=>{placing=!placing;place.textContent=placing?'Placering aktiv – tryck på ritningen':'Aktivera placering';place.setAttribute('aria-pressed',String(placing));});drawings.append(place,el('p','Grön: provad OK · Röd: anmärkning · Grå: återstår / ej åtkomlig. Tryck på markeringen för detaljer.'));
  const scroller=el('div',undefined,'drawing-scroll'),stage=el('div',undefined,'drawing-stage'),canvas=el('canvas'),overlay=el('div',undefined,'drawing-overlay'),info=el('div');stage.append(canvas,overlay);scroller.append(stage);drawings.append(scroller,info);stage.hidden=true;
  const zoom=select(drawings,'Zoom',[['100','Anpassa bredd'],['150','150 %'],['200','200 %'],['300','300 %']]);zoom.onchange=()=>stage.style.width=zoom.value+'%';
  function pins(){overlay.replaceChildren();for(const pin of state.pins.filter(p=>p.docId===ds.value&&p.page===Number(page.value))){const d=register.devices.find(d=>d.id===pin.deviceId);if(!d)continue;const latest=register.events.filter(e=>e.kind==='test'&&e.deviceId===d.id&&e.generation===d.generation&&e.date>=from.value&&e.date<=to.value).sort((a,b)=>b.date.localeCompare(a.date)||b.recordedAt.localeCompare(a.recordedAt))[0],colour=latest?.status==='Provad – OK'?'ok':latest?.status==='Provad – anmärkning'?'fault':'remaining';const mark=btn(window.detectorData.address(d,f.central),e=>{e.stopPropagation();info.replaceChildren(el('h4',window.detectorData.label(d,f.central)),el('p',d.typ+' · '+d.placering),el('p',latest?latest.date+' · '+latest.status+(latest.note?' · '+latest.note:''):'Återstår i vald period'));for(const e0 of register.events.filter(e=>e.deviceId===d.id).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt)))info.append(el('p',e0.date+' · '+(e0.status||'Byte')+' · '+(e0.note||'')));info.append(btn('Registrera provning',()=>window.dispatchEvent(new CustomEvent('field-test',{detail:{id:f.id,deviceId:d.id}}))),btn('Flytta markering',()=>{device.value=d.id;placing=true;place.textContent='Placering aktiv – tryck på ny plats';}));});mark.className='drawing-pin '+colour;mark.style.left=(pin.x*100)+'%';mark.style.top=(pin.y*100)+'%';mark.setAttribute('aria-label',window.detectorData.label(d,f.central)+' · '+(latest?.status||'Återstår'));overlay.append(mark);}}
  async function draw(){const token=++renderVersion;stage.hidden=true;info.replaceChildren();try{renderTask?.cancel();if(docHandle){await docHandle.destroy();docHandle=null;}if(!ds.value)return;api.date(from.value);api.date(to.value);if(from.value>to.value)throw Error('Kontrollera datumperioden.');const content=await db.read('docfile:'+ds.value);if(typeof content!=='string')throw Error('Dokumentfilen saknas.');let width,height;if(content.startsWith('data:application/pdf;')){const pdfjs=await import('./pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./pdf.worker.min.mjs',location.href).href;const pdf=await pdfjs.getDocument({data:Uint8Array.from(atob(content.split(',')[1]),c=>c.charCodeAt(0)),useSystemFonts:true,useWasm:false,isEvalSupported:false}).promise;if(token!==renderVersion){await pdf.destroy();return;}docHandle=pdf;page.max=String(pdf.numPages);const number=Number(page.value);if(!Number.isInteger(number)||number<1||number>pdf.numPages)throw Error('Välj sida 1–'+pdf.numPages);const p=await pdf.getPage(number),base=p.getViewport({scale:1}),viewport=p.getViewport({scale:Math.min(2,1800/Math.max(base.width,base.height))});width=viewport.width;height=viewport.height;canvas.width=width;canvas.height=height;renderTask=p.render({canvasContext:canvas.getContext('2d'),viewport});await renderTask.promise;}else if(/^data:image\/(jpeg|png|webp);/.test(content)){page.value='1';page.max='1';const image=new Image();image.src=content;await image.decode();if(token!==renderVersion)return;const scale=Math.min(1,1800/Math.max(image.width,image.height));width=image.width*scale;height=image.height*scale;canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(image,0,0,width,height);}else throw Error('Välj en PDF eller bild.');if(token!==renderVersion)return;stage.hidden=false;pins();}catch(e){if(token===renderVersion&&e.name!=='RenderingCancelledException'){error(Error('Ritningen kunde inte visas: '+e.message));}}}
  ds.dataset.drawing='doc';page.dataset.drawing='page';from.dataset.drawing='from';to.dataset.drawing='to';zoom.dataset.drawing='zoom';root.cleanup=()=>{renderVersion++;renderTask?.cancel();docHandle?.destroy();};if(drawingState.doc&&docs.some(d=>d.id===drawingState.doc)){ds.value=drawingState.doc;page.value=drawingState.page||'1';from.value=drawingState.from||from.value;to.value=drawingState.to||to.value;zoom.value=drawingState.zoom||'100';stage.style.width=zoom.value+'%';draw();}ds.onchange=()=>{page.value='1';draw();};page.onchange=draw;from.onchange=draw;to.onchange=draw;
  stage.onclick=async e=>{if(!placing||!device.value||stage.hidden)return;const rect=stage.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height;const docId=ds.value,pageno=Number(page.value),deviceId=device.value;placing=false;try{await save(s=>{const old=s.pins.find(p=>p.docId===docId&&p.page===pageno&&p.deviceId===deviceId);if(old)Object.assign(old,{x,y});else s.pins.push({id:crypto.randomUUID(),docId,page:pageno,deviceId,x,y});});}catch(e){error(e);}};
  const planning=panel('planning','3 · Planera nästa provning');const pf=el('form',undefined,'import-grid'),pfrom=input(pf,'Period från','from',new Date().getFullYear()+'-01-01','date'),pto=input(pf,'Period till','to',window.orderData.today(),'date'),count=input(pf,'Antal att föreslå','count','10','number');count.min='1';const propose=el('button','Föreslå urval','primary');pf.append(propose);planning.append(el('p','Oprovade under perioden prioriteras, sedan äldsta registrering. Du väljer omfattning och godkänner listan.'),pf);const proposal=el('div');planning.append(proposal);
  pf.onsubmit=e=>{e.preventDefault();try{const all=api.candidates(register,pfrom.value,pto.value,f.central),n=Number(count.value);if(!Number.isInteger(n)||n<1)throw Error('Ange ett helt antal större än noll.');proposal.replaceChildren(el('p',all.length+' återstår under perioden. Justera urvalet nedan.'));const checks=[];for(const [i,d]of all.entries()){const l=el('label',undefined,'check-row'),c=el('input');c.type='checkbox';c.checked=i<n;l.append(c,document.createTextNode(window.detectorData.label(d,f.central)+' · '+d.placering));checks.push({c,d});proposal.append(l);}proposal.append(btn('Godkänn och spara arbetslista',async()=>{try{const devices=checks.filter(x=>x.c.checked).map(x=>({id:x.d.id,generation:x.d.generation}));if(!devices.length)throw Error('Välj minst en detektor.');await save(s=>s.plans.unshift({id:crypto.randomUUID(),createdAt:new Date().toISOString(),from:pfrom.value,to:pto.value,devices}));}catch(e){error(e);}}));}catch(e){error(e);}};
  for(const plan of state.plans){const row=el('article',undefined,'job-card'),remaining=plan.devices.filter(ref=>{const d=register.devices.find(d=>d.id===ref.id);return d&&!window.detectorData.tested(d,register.events,plan.from,plan.to);});row.append(el('strong',plan.from+' – '+plan.to+' · '+remaining.length+' återstår av '+plan.devices.length),btn('Starta sparad arbetslista',()=>window.dispatchEvent(new CustomEvent('field-test',{detail:{id:f.id,deviceIds:remaining.map(x=>x.id)}}))),btn('Exportera arbetslista',()=>download('arbetslista.csv',window.detectorData.csv([['Beteckning','Typ','Placering','Återstår'],...plan.devices.map(ref=>{const d=register.devices.find(d=>d.id===ref.id);return d?[window.detectorData.label(d,f.central),d.typ,d.placering,remaining.some(x=>x.id===d.id)?'Ja':'Nej']:['Borttagen detektor',ref.id,'',''];})]),'text/csv;charset=utf-8')));planning.append(row);}
  const materials=panel('materials','4 · Material & reservdelar');const mf=el('form',undefined,'import-grid'),mi={};mi.name=input(mf,'Artikel / batterityp','name');mi.name.required=true;mi.model=input(mf,'Modell / artikelnummer','model');mi.quantity=input(mf,'Antal','quantity','1','number');mi.quantity.min='1';mi.quantity.step='1';mi.installed=input(mf,'Installationsdatum','installed','','date');mi.state=select(mf,'Materialstatus',['Installerat','Behöver beställas','Beställt','Att ta med','Förbrukat'].map(t=>[t,t]));mi.note=input(mf,'Materialanteckning','note','','textarea');let editId='';const ms=el('button','Spara material','primary');mf.append(ms);mf.onsubmit=async e=>{e.preventDefault();ms.disabled=true;try{const m=api.material({id:editId,...Object.fromEntries(Object.entries(mi).map(([k,n])=>[k,n.value]))});await save(s=>{const i=s.materials.findIndex(x=>x.id===m.id);if(i<0)s.materials.push(m);else s.materials[i]=m;});}catch(e){error(e);ms.disabled=false;}};materials.append(mf);
  for(const m of state.materials){const row=el('article',undefined,'job-card');row.append(el('strong',m.quantity+' × '+m.name+' · '+m.state),el('p',[m.model,m.installed?'Installerat '+m.installed:'',m.note].filter(Boolean).join(' · ')),btn('Redigera material',()=>{editId=m.id;for(const [k,n]of Object.entries(mi))n.value=m[k]||'';mf.scrollIntoView({block:'center'});}));materials.append(row);}const legacy=api.read(data,'materiel:'+f.id,[]);if(legacy.length){materials.append(el('h4','Tidigare materiallista'));for(const m of legacy)materials.append(el('p',(m.antal||1)+' × '+(m.artikel||'')));}
  materials.append(btn('Exportera beställningslista',()=>download('material.csv',window.detectorData.csv([['Artikel','Modell','Antal','Status','Anteckning'],...state.materials.filter(m=>m.state!=='Installerat'&&m.state!=='Förbrukat').map(m=>[m.name,m.model,m.quantity,m.state,m.note]),...legacy.map(m=>[m.artikel,'',m.antal,'Tidigare materiallista',''])]),'text/csv;charset=utf-8')));
  const prep=panel('prep','5 · Förbered nästa besök'),notes=input(prep,'Att tänka på nästa gång','prep',state.prep||'','textarea');quick(notes);prep.append(btn('Spara besöksanteckning',async()=>{try{await save(s=>s.prep=notes.value.trim());}catch(e){error(e);}}));const summary=()=>{const pending=api.read(data,'issues:'+f.id,[]).filter(i=>i.status!=='Kontrollerad'),last=api.read(data,'service-reports:'+f.id,[]).sort((a,b)=>b.date.localeCompare(a.date))[0],next=orders.filter(o=>o.status!=='Klart').sort((a,b)=>(a.planeradTill||'9999').localeCompare(b.planeradTill||'9999'))[0];return [f.namn+' · '+(f.anlNr||''),f.adress||'','Nästa uppdrag: '+(next?[next.planeradTill,next.ordernummer,next.uppdragstyp].filter(Boolean).join(' · '):'Inte planerat'),'Kontakt: '+[f.kontakt,f.tele].filter(Boolean).join(' · '),'Skötare 1: '+[f.skotare1,f.skotare1Tele].filter(Boolean).join(' · '),'Skötare 2: '+[f.skotare2,f.skotare2Tele].filter(Boolean).join(' · '),'','KVARSTÅENDE FEL',...pending.map(i=>i.title+' · '+i.status+' · '+i.note),...(!pending.length?['Inga registrerade kvarstående fel.']:[]),'','MATERIAL / ATT TA MED',...state.materials.filter(m=>!['Installerat','Förbrukat'].includes(m.state)).map(m=>m.quantity+' × '+m.name+' · '+m.model+' · '+m.state),...legacy.map(m=>(m.antal||1)+' × '+m.artikel),'','FÖREGÅENDE BESÖK',last?last.date+' · '+last.summary:'Ingen servicerapport sparad.','','BESÖKSANTECKNING',notes.value].join('\n');};const overview=el('pre',undefined,'prep-summary');prep.append(btn('Sammanställ inför nästa besök',()=>overview.textContent=summary()),btn('Hämta besöksunderlag',()=>download('besoksunderlag.txt',summary(),'text/plain;charset=utf-8')),overview);
  const transfer=panel('transfer','6 · Överför objekt mellan enheter');transfer.append(el('p','Exporten innehåller detta objekt med dokument, arbetsorder, protokoll, utkast och historik. Dela filen själv till den andra enheten och importera under Offline & backup. Snabbtexter och mallar är enhetsinställningar och följer med i full säkerhetskopia.'));
  transfer.append(btn('Exportera detta objekt',async()=>{try{const pkg=api.packageObject(await db.snapshot(),f.id);download('objekt_'+String(f.anlNr||'export').replace(/[^\p{L}\p{N}_-]/gu,'_')+'.json',JSON.stringify(pkg));}catch(e){error(e);}}));
  const texts=panel('texts','7 · Egna snabbtexter'),textForm=el('form'),textArea=input(textForm,'En snabbtext per rad','phrases',(prefs.phrases||api.phrases).join('\n'),'textarea');textForm.append(el('button','Spara snabbtexter','primary'));textForm.onsubmit=async e=>{e.preventDefault();try{const phrases=[...new Set(textArea.value.split('\n').map(s=>s.trim()).filter(Boolean))];await db.updateRecord('field-preferences',{templates:api.templates,phrases:api.phrases},p=>({...p,phrases}));document.querySelectorAll('.quick-texts').forEach(n=>n.remove());document.querySelectorAll('[data-quick]').forEach(n=>{delete n.dataset.quick;quick(n);});refresh();}catch(e){error(e);}};texts.append(el('p','Finns vid detektorprovning, nya fel, åtgärder och besöksanteckningar. Du kan alltid skriva och komplettera manuellt.'),textForm);
 }
 function transferPanel(){const settings=document.getElementById('settings'),section=el('section',undefined,'settings-card');section.append(el('h2','Importera ett objektpaket'),el('p','Välj exportfilen från den andra enheten. Skillnader visas innan sparande. Befintliga uppgifter behålls som standard.'));const file=input(section,'Objektpaket (JSON, högst 100 MB)','package','','file');file.accept='.json,application/json';const preview=el('div'),msg=el('p');msg.setAttribute('role','status');section.append(msg,preview);settings.append(section);file.onchange=async()=>{preview.replaceChildren();try{if(!file.files[0])return;if(file.files[0].size>100*1024*1024)throw Error('Filen är större än 100 MB.');const pkg=api.validatePackage(JSON.parse(await file.files[0].text())),before=await db.snapshot(),rows=api.previewPackage(pkg,before);msg.textContent='Objekt: '+api.read(pkg.data,'facilities')[0].namn+' · '+rows.filter(r=>r.kind==='Ny').length+' nya poster · '+rows.filter(r=>r.kind==='Skillnad').length+' skillnader.';preview.append(el('p','Valet Använd inkommande ersätter hela den visade posten eller registret. Kontrollera särskilt historik och dokument. Spara gärna en full säkerhetskopia först.'));
   for(const row of rows.filter(r=>r.kind!=='Oförändrad')){const card=el('details',undefined,'job-card');card.append(el('summary',row.label+' · '+row.kind));const choice=select(card,'Välj uppgifter',[['keep','Behåll på denna enhet'],['import','Använd inkommande']],row.use?'import':'keep');choice.onchange=()=>row.use=choice.value==='import';const explain=value=>{if(value===undefined)return 'Saknas';if(row.key.startsWith('docfile:'))return 'Dokumentfil · '+Math.round(value.length*.75/1024)+' kB';return JSON.stringify(JSON.parse(value),(k,v)=>typeof v==='string'&&v.startsWith('data:')?'[Bifogad fil]':v,2);};card.append(el('h4','På denna enhet'),el('pre',explain(row.before),'transfer-diff'),el('h4','Inkommande'),el('pre',explain(row.after),'transfer-diff'));preview.append(card);}
   const save=btn('Importera valda uppgifter',async()=>{save.disabled=true;try{const writes=api.packageWrites(rows,before);if(!Object.keys(writes).length)throw Error('Inga nya eller ändrade uppgifter valda.');const after={...before,...writes};api.validatePackage(api.packageObject(after,pkg.facilityId));await db.commitRecords(before,writes);preview.replaceChildren();file.value='';msg.textContent='Objektpaketet är importerat. Befintliga uppgifter som du valde att behålla är kvar.';window.dispatchEvent(new Event('objects-imported'));refresh();}catch(e){msg.textContent=e.message;save.disabled=false;}});preview.append(save);
  }catch(e){msg.textContent=e.message;}};
 }
 window.fieldUI={mount,quick};transferPanel();window.localReady.then(()=>quick(document.getElementById('det-test-note')));
})();
