(() => {
 'use strict';
 const $=id=>document.getElementById(id),api=window.objectLists;let parsed=null,decisions=[],prepared=null,baseline='',sequence=0;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const mapping=()=>[...$('import-mapping').querySelectorAll('select')].map(s=>s.value);
 function fail(error){$('import-result').textContent=error.message;$('commit-objects').disabled=true;prepared=null;}
 function invalidate(){sequence++;parsed=null;prepared=null;decisions=[];$('import-mapping').replaceChildren();$('import-preview').replaceChildren();$('commit-objects').disabled=true;$('import-result').textContent='Granska listan efter dina ändringar.';}
 async function preview(){const current=++sequence;$('commit-objects').disabled=true;try{const data=await window.localData.snapshot();if(current!==sequence)return;baseline=JSON.stringify([data.facilities||'[]',data.workorders||'[]']);prepared=window.orderData.prepareImport(parsed.rows,mapping(),JSON.parse(data.facilities||'[]'),JSON.parse(data.workorders||'[]'),decisions);renderReview();$('import-result').textContent=`${prepared.review.filter(r=>r.action!=='Hoppas över').length} rader importeras. Granska ändringarna per rad. Tomma fält bevarar sparade värden.`;$('commit-objects').disabled=false;}catch(error){fail(error);renderReview();}}
 function renderReview(){if(!parsed)return;const table=el('table'),header=el('tr');['Rad','Åtgärd','Nytt objektnummer','Objekt / order','Ändringar'].forEach(s=>header.append(el('th',s)));table.append(header);
  parsed.rows.forEach((row,index)=>{const tr=el('tr');tr.append(el('td',String(index+2)));const choice=el('select');choice.setAttribute('aria-label',`Åtgärd rad ${index+2}`);for(const [value,label]of [['update','Uppdatera / skapa'],['skip','Hoppa över'],['new','Nytt objekt']]){const op=el('option',label);op.value=value;choice.append(op);}choice.value=decisions[index]?.action||'update';choice.onchange=()=>{decisions[index]={...decisions[index],action:choice.value};preview();};const td=el('td');td.append(choice);tr.append(td);const number=el('input');number.setAttribute('aria-label',`Nytt objektnummer rad ${index+2}`);number.value=decisions[index]?.number||'';number.disabled=choice.value!=='new';number.onchange=()=>{decisions[index]={...decisions[index],number:number.value};preview();};const numberCell=el('td');numberCell.append(number);tr.append(numberCell);const review=prepared?.review[index];tr.append(el('td',review?.item?`${review.item.anlNr} · ${review.item.namn} · ${review.job?.ordernummer||'Ingen order'}`:row.slice(0,4).join(' · ')));const detail=el('details'),summary=el('summary',review?`${review.changes.length} ändringar`:'Rätta valen för att granska');detail.append(summary);for(const change of review?.changes||[])detail.append(el('p',`${change.label}: ${change.before||'(tomt)'} → ${change.after||'(tomt)'}`));const d=el('td');d.append(detail);tr.append(d);table.append(tr);});$('import-preview').replaceChildren(table);
 }
 $('object-list-text').oninput=invalidate;$('list-separator').onchange=invalidate;
 $('object-list-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw Error('Filen får vara högst 5 MB.');$('object-list-text').value=await file.text();invalidate();}catch(error){fail(error);}finally{e.target.value='';}};
 $('review-objects').onclick=async()=>{try{parsed=api.parse($('object-list-text').value,$('list-separator').value);decisions=[];$('import-mapping').replaceChildren();parsed.headers.forEach((title,i)=>{const label=el('label',title||`Kolumn ${i+1}`),select=el('select');select.setAttribute('aria-label',`Koppla kolumn ${title||i+1}`);for(const [key,text]of [['','Hoppa över'],...api.fields]){const op=el('option',text);op.value=key;select.append(op);}select.value=parsed.mapping[i];select.onchange=preview;label.append(select);$('import-mapping').append(label);});await preview();}catch(error){fail(error);}};
 $('commit-objects').onclick=async()=>{if(!prepared)return;const ready=prepared;$('commit-objects').disabled=true;try{const data=await window.localData.snapshot();if(JSON.stringify([data.facilities||'[]',data.workorders||'[]'])!==baseline){await preview();$('import-result').textContent='Uppgifterna har ändrats sedan granskningen. Granska den uppdaterade förhandsvisningen före import.';return;}if(!confirm('Spara de granskade objekt- och orderändringarna? Befintliga protokoll behålls.')){$('commit-objects').disabled=false;return;}await window.localData.restore({app:'SäkerhetSnabben',data:{facilities:JSON.stringify(ready.facilities),workorders:JSON.stringify(ready.workorders)}});window.dispatchEvent(new Event('objects-imported'));invalidate();$('object-list-text').value='';$('import-result').textContent='Importen är klar. Objekt och arbetsorder är sparade på telefonen.';}catch(error){fail(error);}};
 $('object-template').onclick=()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+api.fields.map(f=>f[1]).join(';')+'\r\n'],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download='objektmall.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
})();
