(() => {
 'use strict';
 const $=id=>document.getElementById(id),api=window.orderData;let facilities=[],orders=[],snapshot={},selectedId='',loading=false;
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const button=(text,fn,cls='secondary')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
 const notify=text=>$('jobs-message').textContent=text;
 const change=()=>window.dispatchEvent(new Event('orders-changed'));
 async function saveOrder(order){const latest=await window.localData.read('workorders',[]);const index=latest.findIndex(o=>o.id===order.id);if(index<0)latest.push(order);else latest[index]=order;await window.storage.set('workorders',JSON.stringify(latest));await refresh();change();}
 function openOrder(order){const f=facilities.find(f=>f.id===order.facilityId);if(!f){notify('Kundobjektet saknas.');return;}window.dispatchEvent(new CustomEvent('open-order',{detail:{id:f.id,order:{...order}}}));}
 function reminder(){let last='';try{last=localStorage.getItem('offline-backup-export')||'';}catch{}const newest=orders.filter(o=>o.completedAt).sort((a,b)=>b.completedAt.localeCompare(a.completedAt))[0]?.completedAt;const stale=!last||Date.now()-Date.parse(last)>7*86400000||newest&&newest>last;$('backup-hint').textContent=stale?'Dags för säkerhetskopia: spara dina senaste objekt, arbetsorder och protokoll.':'Säkerhetskopia exporterad '+new Date(last).toLocaleDateString('sv-SE')+'. Kontrollera att filen finns kvar.';}
 async function refresh(){if(loading)return;loading=true;try{snapshot=await window.localData.snapshot();facilities=JSON.parse(snapshot.facilities||'[]');orders=JSON.parse(snapshot.workorders||'[]');const migrated=api.migrate(facilities,orders);if(migrated.length!==orders.length){orders=migrated;await window.storage.set('workorders',JSON.stringify(orders));}render();renderCard();reminder();}catch(error){notify('Kunde inte läsa arbetsorder: '+error.message);}finally{loading=false;}}
 function render(){const date=$('jobs-date').value,kind=$('jobs-kind').value,status=$('jobs-status').value,scope=$('jobs-scope').value;
  const rows=orders.filter(o=>(scope==='all'||scope==='late'&&o.planeradTill&&o.planeradTill<api.today()&&o.status!=='Klart'||scope==='day'&&o.planeradTill===date)&&(!kind||o.uppdragstyp===kind)&&(!status||o.status===status)).sort((a,b)=>(a.planeradTill||'9999').localeCompare(b.planeradTill||'9999')||a.ordernummer.localeCompare(b.ordernummer,'sv',{numeric:true}));
  const sort=$('jobs-sort').value;const value=o=>o[sort]??facilities.find(f=>f.id===o.facilityId)?.[sort]??'';rows.sort((a,b)=>String(value(a)).localeCompare(String(value(b)),'sv',{numeric:true}));
  $('jobs-list').replaceChildren();$('jobs-count').textContent=rows.length+' uppdrag';
  if(!rows.length)$('jobs-list').append(el('p','Inga uppdrag i detta urval. Välj Alla eller skapa en arbetsorder.','muted'));
  for(const o of rows){const f=facilities.find(f=>f.id===o.facilityId);const card=el('article',undefined,'job-card');card.append(el('strong',`${o.ordernummer||'Utan ordernummer'} · ${o.uppdragstyp||'Typ saknas'} · ${o.status}`),el('p',`${f?.namn||'Objekt saknas'} · ${f?.anlNr||''} · ${f?.adress||''}`),el('p','Planerad: '+(o.planeradTill||'Ej planerad'),'muted'));const actions=el('div',undefined,'button-row');actions.append(button('Öppna protokoll',()=>openOrder(o)),button('Objektkort',()=>showCard(o.facilityId)),button('Redigera order',()=>editOrder(o)));if(o.status==='Planerat')actions.append(button('Påbörja',()=>saveOrder({...o,status:'Påbörjat'}).catch(e=>notify(e.message))));if(o.status!=='Klart')actions.append(button('Kontrollera & avsluta',()=>reviewCompletion(o)));else actions.append(button('Återöppna',()=>saveOrder({...o,status:'Påbörjat',completedAt:null,completionNote:''}).catch(e=>notify(e.message))));card.append(actions);$('jobs-list').append(card);}
 }
 function editOrder(order){const form=$('order-form');form.hidden=false;form.dataset.id=order?.id||'';const select=$('order-facility');select.replaceChildren();for(const f of facilities){const op=el('option',`${f.anlNr||'Utan nummer'} · ${f.namn}`);op.value=f.id;select.append(op);}select.value=order?.facilityId||selectedId||facilities[0]?.id||'';select.disabled=!!order;for(const key of ['ordernummer','uppdragstyp','planeradTill','notes'])$('order-'+key).value=order?.[key]||'';form.scrollIntoView({block:'center'});}
 async function reviewCompletion(order){await refresh();const fresh=orders.find(o=>o.id===order.id);if(!fresh)return;const drafts=Object.entries(snapshot).filter(([k])=>k.startsWith('draft:')).map(([k,v])=>({...JSON.parse(v),proto:k.split(':').at(-1)}));const reports=JSON.parse(snapshot['history-index']||'[]');const issues=api.completion(fresh,facilities.find(f=>f.id===fresh.facilityId),drafts,reports);const panel=$('completion-panel');panel.replaceChildren(el('h3','Kontroll före avslut'),el('p',issues.length?'Följande behöver uppmärksammas. Återgå och rätta eller dokumentera varför uppdraget avslutas ändå.':'Grundkontrollen är klar. Kontrollera att uppdragets dokumentation är färdig.'));if(issues.length){const ul=el('ul');issues.forEach(i=>ul.append(el('li',i)));panel.append(ul);}const label=el('label','Avslutsanteckning'+(issues.length?' (krävs vid kvarstående punkter)':''));const note=el('textarea');note.rows=3;label.append(note);panel.append(label);const error=el('p');error.setAttribute('role','alert');const finish=button('Markera arbetsordern klar',async()=>{if(issues.length&&!note.value.trim()){error.textContent='Skriv en förklaring eller rätta punkterna först.';return;}finish.disabled=true;try{await saveOrder({...fresh,status:'Klart',completedAt:new Date().toISOString(),completionNote:note.value.trim(),completionIssues:issues});panel.hidden=true;notify('Arbetsordern är klar. Kom ihåg att spara en säkerhetskopia.');}catch(e){error.textContent=e.message;finish.disabled=false;}},'primary');panel.append(error,finish,button('Återgå',()=>panel.hidden=true));panel.hidden=false;panel.scrollIntoView({block:'center'});}
 async function showCard(id){selectedId=id;try{await window.serviceData.syncIssues(id);await refresh();renderCard();$('customer-card').scrollIntoView({block:'start'});}catch(e){notify(e.message);}}
 function renderCard(){const f=facilities.find(f=>f.id===selectedId),card=$('customer-card');card.hidden=!f;if(!f)return;card.replaceChildren(el('h2',f.namn),el('p',`${f.anlNr||'Utan nummer'} · ${f.adress||''}`));const actions=el('div',undefined,'button-row');actions.append(button('Detektorer & provning',()=>window.dispatchEvent(new CustomEvent('open-detectors',{detail:{id:f.id}}))),button('Redigera objekt / dokument',()=>window.dispatchEvent(new CustomEvent('open-customer',{detail:{id:f.id}}))),button('Ny arbetsorder',()=>editOrder(null)),button('Stäng objektkort',()=>{selectedId='';card.hidden=true;}));card.append(actions);const dl=el('dl',undefined,'customer-details');for(const [key,label]of window.objectLists.fields.filter(([k])=>!['ordernummer','uppdragstyp','planeradTill'].includes(k))){if(!f[key])continue;dl.append(el('dt',label),el('dd',String(f[key])));}card.append(dl);
  const work=orders.filter(o=>o.facilityId===f.id);card.append(el('h3','Arbetsorder'));for(const o of work){card.append(button(`${o.ordernummer||'Utan nummer'} · ${o.uppdragstyp} · ${o.planeradTill||'Ej planerad'} · ${o.status}`,()=>editOrder(o)));if(o.completionNote)card.append(el('p','Avslut: '+o.completionNote));}
  window.fieldUI.mount(card,f,snapshot);window.serviceUI.mount(card,f,snapshot);
  const history=JSON.parse(snapshot['history-index']||'[]').filter(r=>r.facilityId===f.id);card.append(el('h3','Tidigare protokoll'));for(const r of history)card.append(button(`${r.proto} · ${r.datum||''} · ${r.orderNumber||'Utan arbetsorder'}`,()=>window.dispatchEvent(new CustomEvent('open-report',{detail:{id:r.id}}))));if(!history.length)card.append(el('p','Inga arkiverade protokoll.'));
  const future=work.filter(o=>o.status!=='Klart'&&o.planeradTill).sort((a,b)=>a.planeradTill.localeCompare(b.planeradTill))[0];card.append(el('p','Nästa planerade uppdrag: '+(future?`${future.planeradTill} · ${future.ordernummer}`:'Inget bokat')));
 }
 $('order-form').onsubmit=async e=>{e.preventDefault();const f=facilities.find(f=>f.id===$('order-facility').value);if(!f){notify('Skapa ett kundobjekt först.');return;}const id=e.target.dataset.id;const old=orders.find(o=>o.id===id);const values={};for(const key of ['ordernummer','uppdragstyp','planeradTill','notes'])values[key]=$('order-'+key).value.trim();if(orders.some(o=>o.id!==id&&o.facilityId===f.id&&o.ordernummer===values.ordernummer)){notify('Det ordernumret finns redan på objektet.');return;}try{await saveOrder(old?{...old,...values}:api.make(f,values));e.target.hidden=true;notify('Arbetsordern sparades.');}catch(error){notify(error.message);}};
 $('new-order').onclick=()=>editOrder(null);$('cancel-order').onclick=()=>$('order-form').hidden=true;$('jobs-date').value=api.today();for(const id of ['jobs-date','jobs-kind','jobs-status','jobs-scope','jobs-sort'])$(id).onchange=render;
 window.addEventListener('service-changed',refresh);window.addEventListener('show-customer',e=>showCard(e.detail.id));window.addEventListener('objects-imported',refresh);window.addEventListener('local-storage-state',e=>{if(e.detail.state==='saved')refresh();});window.addEventListener('backup-exported',reminder);window.localReady.then(refresh).catch(e=>notify(e.message));
})();
