(() => {
 'use strict';
 const api=window.serviceData,el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn,cls='secondary')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
 const root=el('div',undefined,'service-hub');let signature='',activeId='',savedReport=null;
 const read=(data,key,fallback)=>JSON.parse(data[key]||JSON.stringify(fallback));
 const changed=()=>window.dispatchEvent(new Event('service-changed'));
 function field(form,label,name,value='',type='text'){const l=el('label',label),input=el(type==='textarea'?'textarea':'input');input.name=name;if(type!=='textarea')input.type=type;else input.rows=3;input.value=value;l.append(input);form.append(l);if(type==='textarea')window.fieldUI?.quick(input);return input;}
 function blobFromData(data){const [header,base64]=data.split(',');if(!/^data:(application\/pdf|image\/(jpeg|png|webp));base64$/.test(header))throw Error('Dokumentformatet kan inte öppnas här.');const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));return new Blob([bytes],{type:header.slice(5,-7)});}
 function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 async function photoData(file){if(file.type==='application/pdf'){const bytes=await file.slice(0,5).text();if(bytes!=='%PDF-')throw Error('Filen är inte en giltig PDF.');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Filen kunde inte läsas.'));r.readAsDataURL(file);});}if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error('Välj PDF, JPEG, PNG eller WebP.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.85);}finally{URL.revokeObjectURL(url);}}
 function mount(container,f,data){container.append(root);const relevant=[f,data['issues:'+f.id],data['docs:'+f.id],data['service-reports:'+f.id],data['history-index'],data.workorders];const next=JSON.stringify(relevant);if(activeId===f.id&&next===signature)return;activeId=f.id;signature=next;root.replaceChildren();savedReport=null;
  const message=el('p');message.setAttribute('role','status');root.append(message);const error=e=>message.textContent=e.message||String(e);
  const gaps=api.missing(f),status=el('section',undefined,'settings-card');status.append(el('h3','Överblick'),el('p',gaps.length?'Uppgifter att komplettera: '+gaps.join(', '):'Grunduppgifterna är ifyllda.',gaps.length?'service-warning':'muted'));
  const history=read(data,'history-index',[]).filter(r=>r.facilityId===f.id).sort((a,b)=>String(b.datum).localeCompare(String(a.datum)));const reports=read(data,'service-reports:'+f.id,[]);const dates=[...history.map(r=>r.datum),...reports.map(r=>r.date)].filter(Boolean).sort();status.append(el('p','Senast dokumenterade besök: '+(dates.at(-1)||'Inget dokumenterat')));
  const contacts=el('div',undefined,'service-grid');for(const [name,phone,email,label]of [[f.kontakt,f.tele,f.epost,'Kontaktperson'],[f.skotare1,f.skotare1Tele,f.skotare1Epost,'Anläggningsskötare 1'],[f.skotare2,f.skotare2Tele,f.skotare2Epost,'Anläggningsskötare 2']]){const c=el('div');c.append(el('strong',label),el('p',name||'Saknas'));if(phone){const a=el('a',phone);a.href='tel:'+phone.replace(/[^+\d]/g,'');c.append(a);}if(email){const a=el('a',email);a.href='mailto:'+encodeURIComponent(email);c.append(el('br'),a);}contacts.append(c);}status.append(contacts,el('p','Centralapparat: '+(f.central||'Saknas')),el('p','Larmsändare: '+(f.larmsandare||'Saknas')));root.append(status);
  const issues=read(data,'issues:'+f.id,[]),pending=issues.filter(i=>i.status!=='Kontrollerad');const faultPanel=el('section',undefined,'settings-card');faultPanel.append(el('h3',`Fel & åtgärder · ${pending.length} kvar att följa upp`));if(pending.length)faultPanel.append(el('p','Dessa fel visas igen vid nästa besök tills de är åtgärdade och kontrollerade.','service-warning'));if(!issues.length)faultPanel.append(el('p','Inga registrerade fel.'));
  const issueForm=el('form',undefined,'import-grid');issueForm.hidden=true;field(issueForm,'Fel / rubrik','title').required=true;field(issueForm,'Beskrivning','note','','textarea').required=true;field(issueForm,'Registrerat av','technician').required=true;const add=el('button','Spara fel','primary');add.type='submit';issueForm.append(add,button('Avbryt',()=>issueForm.hidden=true));issueForm.onsubmit=async event=>{event.preventDefault();add.disabled=true;const v=Object.fromEntries(new FormData(issueForm));try{await window.localData.updateRecord('issues:'+f.id,[],items=>{items.push({id:crypto.randomUUID(),title:v.title.trim(),note:v.note.trim(),status:'Öppen',sources:[],createdAt:new Date().toISOString(),timeline:[{at:new Date().toISOString(),status:'Öppen',note:v.note.trim(),technician:v.technician.trim()}]});return items;});changed();}catch(e){error(e);add.disabled=false;}};faultPanel.append(button('Registrera nytt fel',()=>issueForm.hidden=false),issueForm);
  for(const issue of [...pending,...issues.filter(i=>i.status==='Kontrollerad')]){const box=el('details',undefined,'job-card');box.open=issue.status!=='Kontrollerad';box.append(el('summary',issue.title+' · '+issue.status),el('p',issue.note));for(const t of issue.timeline||[])box.append(el('p',`${new Date(t.at).toLocaleString('sv-SE')} · ${t.status} · ${t.technician}: ${t.note}`,'muted'));
   const form=el('form',undefined,'import-grid');const l=el('label','Ny status'),select=el('select');select.name='status';for(const state of api.states.filter(s=>s!==issue.status&&(s!=='Kontrollerad'||issue.status==='Åtgärdad'))){const o=el('option',state);select.append(o);}l.append(select);form.append(l);field(form,'Åtgärd / kontroll','note','','textarea').required=true;field(form,'Tekniker','technician').required=true;const save=el('button','Spara status','primary');save.type='submit';form.append(save);form.onsubmit=async event=>{event.preventDefault();save.disabled=true;const v=Object.fromEntries(new FormData(form));try{await window.localData.updateRecord('issues:'+f.id,[],items=>{const i=items.findIndex(x=>x.id===issue.id);if(i<0||items[i].status!==issue.status)throw Error('Felet har ändrats. Öppna objektkortet igen.');items[i]=api.transition(items[i],v.status,v.note,v.technician);return items;});changed();}catch(e){error(e);save.disabled=false;}};box.append(form);faultPanel.append(box);
  }root.append(faultPanel);
  const docs=read(data,'docs:'+f.id,[]),docPanel=el('section',undefined,'settings-card');docPanel.append(el('h3','Ritningar, bilder & dokument offline'),el('p','Filerna sparas på denna enhet och ingår i säkerhetskopian. Bilder anpassas till högst 1600 pixlar.'));
  const upload=el('form',undefined,'import-grid'),fileLabel=el('label','PDF eller bild (högst 15 MB)'),file=el('input');file.type='file';file.accept='application/pdf,image/jpeg,image/png,image/webp';file.required=true;fileLabel.append(file);upload.append(fileLabel);field(upload,'Beskrivning, exempelvis Centralapparat i entrén','description').required=true;const uploadButton=el('button','Spara på objektet','primary');uploadButton.type='submit';upload.append(uploadButton);upload.onsubmit=async event=>{event.preventDefault();uploadButton.disabled=true;try{const selected=file.files[0];if(!selected||selected.size>15*1024*1024)throw Error('Välj en fil på högst 15 MB.');const content=await photoData(selected),description=new FormData(upload).get('description').trim();const image=content.startsWith('data:image/');await window.localData.attachDocument(f.id,{id:crypto.randomUUID(),namn:selected.name.replace(/\.[^.]+$/,image?'.jpg':'.pdf'),mime:image?'image/jpeg':'application/pdf',description,date:window.orderData.today(),kategori:'BL401',typ:image?'foto':'ritning'},content);changed();}catch(e){error(e);uploadButton.disabled=false;}};docPanel.append(upload);
  const viewer=el('div');for(const d of docs){const card=el('article',undefined,'job-card');card.append(el('strong',d.description||d.namn),el('p',d.namn+' · '+(d.date||'')));card.append(button('Öppna offline',async()=>{try{const content=await window.localData.read('docfile:'+d.id);if(!content)throw Error('Filen saknas i lagringen.');const blob=blobFromData(content),url=URL.createObjectURL(blob);viewer.replaceChildren();const close=button('Stäng dokument',()=>{viewer.replaceChildren();URL.revokeObjectURL(url);});if(blob.type==='application/pdf'){const frame=el('iframe');frame.title=d.description||d.namn;frame.src=url;frame.style.cssText='width:100%;height:65vh;border:1px solid #ccc';viewer.append(close,frame);}else{const img=el('img');img.src=url;img.alt=d.description||d.namn;img.style.maxWidth='100%';viewer.append(close,img);}viewer.append(button('Hämta fil',()=>download(blob,d.namn)));}catch(e){error(e);}}));card.append(button('Ändra beskrivning',async()=>{const text=prompt('Beskrivning',d.description||'');if(text===null)return;try{await window.localData.updateRecord('docs:'+f.id,[],list=>list.map(x=>x.id===d.id?{...x,description:text.trim()}:x));changed();}catch(e){error(e);}}));docPanel.append(card);}docPanel.append(viewer);root.append(docPanel);
  const reportPanel=el('section',undefined,'settings-card');reportPanel.append(el('h3','Samlad servicerapport'),el('p','Granska utfört arbete, provningsresultat, fel och bilder innan du sparar rapporten och skapar PDF.'));
  const form=el('form',undefined,'import-grid'),date=field(form,'Besöksdatum','date',window.orderData.today(),'date');date.required=true;field(form,'Tekniker','technician').required=true;const ol=el('label','Arbetsorder'),os=el('select');os.name='orderId';const none=el('option','Alla registreringar på objektet för datumet');none.value='';os.append(none);for(const o of read(data,'workorders',[]).filter(o=>o.facilityId===f.id)){const option=el('option',o.ordernummer+' · '+o.uppdragstyp);option.value=o.id;os.append(option);}ol.append(os);form.append(ol);field(form,'Utfört arbete','summary','','textarea').required=true;
  for(const d of docs.filter(d=>/^image\//.test(d.mime))){const l=el('label'),c=el('input');c.type='checkbox';c.name='photo';c.value=d.id;l.append(c,document.createTextNode(' Ta med bild: '+(d.description||d.namn)));form.append(l);}
  const review=el('button','Granska servicerapport','primary');review.type='submit';form.append(review);reportPanel.append(form);const preview=el('div');reportPanel.append(preview);
  form.onsubmit=async event=>{event.preventDefault();review.disabled=true;try{const values=new FormData(form),fresh=await window.localData.snapshot(),facility=read(fresh,'facilities',[]).find(x=>x.id===f.id);if(!facility)throw Error('Objektet saknas.');const register=read(fresh,'detectors:'+f.id,{events:[]});const order=read(fresh,'workorders',[]).find(o=>o.id===values.get('orderId'));const photos=[];for(const id of values.getAll('photo')){const meta=docs.find(d=>d.id===id);const content=await window.localData.read('docfile:'+id);if(content&&meta)photos.push({data:content,name:meta.namn,description:meta.description||''});}
   const fieldwork=read(fresh,'fieldwork:'+f.id,window.fieldData.empty());const report={checklists:fieldwork.visits.filter(v=>v.date===values.get('date')&&(!order||v.orderId===order.id)),materials:fieldwork.materials,visitNote:fieldwork.prep||'',id:crypto.randomUUID(),createdAt:new Date().toISOString(),facility:structuredClone(facility),date:values.get('date'),technician:values.get('technician').trim(),summary:values.get('summary').trim(),orderId:order?.id||'',orderNumber:order?.ordernummer||'',tests:window.detectorData.protocolEvents(register,order?.id,values.get('date'),facility.central),issues:await window.localData.read('issues:'+f.id,[]),photos,documents:docs.map(d=>({namn:d.namn,description:d.description||''}))};
   preview.replaceChildren(el('h4','Granska före sparande'),el('p',report.facility.namn+' · '+report.date+' · '+report.technician),el('p',report.summary),el('p',`${report.tests.length} detektorresultat · ${report.issues.length} felposter · ${report.photos.length} valda bilder`));for(const t of report.tests)preview.append(el('p',t.label+' · '+t.status+(t.note?' · '+t.note:'')));for(const i of report.issues)preview.append(el('p',i.title+' · '+i.status+' · '+i.note));
   preview.append(button('Spara granskad rapport & skapa PDF',async()=>{try{const blob=await api.pdf(report);await window.localData.updateRecord('service-reports:'+f.id,[],list=>list.some(r=>r.id===report.id)?list:[report,...list]);savedReport={blob,report};download(blob,filename(report));changed();}catch(e){error(e);}},'primary'));
  }catch(e){error(e);}finally{review.disabled=false;}};
  reportPanel.append(el('h4','Sparade servicerapporter'));for(const report of reports){const row=el('article',undefined,'job-card');row.append(el('strong',report.date+' · '+report.technician),el('p',report.summary));let ready=null;const actions=el('div',undefined,'button-row'),share=button('Dela PDF',async()=>{if(!ready)return;try{const file=new File([ready],filename(report),{type:'application/pdf'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Servicerapport'});else download(ready,filename(report));}catch(e){if(e.name!=='AbortError')error(e);}});share.disabled=true;actions.append(button('Hämta PDF',async()=>{try{ready=await api.pdf(report);share.disabled=false;download(ready,filename(report));}catch(e){error(e);}}),share);row.append(actions);reportPanel.append(row);}root.append(reportPanel);
 }
 function filename(report){return 'Servicerapport_'+String(report.facility.anlNr||report.facility.namn).replace(/[^\p{L}\p{N}_-]/gu,'_')+'_'+report.date+'.pdf';}
 window.serviceUI={mount};
})();
